- name: 'Get root cron Content'
  tags: 'get-cron-root'
  shell:
    cmd: 'cat /var/spool/cron/crontabs/root'
  register: cron_root
  ignore_errors: yes
  when: ansible_distribution == 'Ubuntu'

#- debug:
#    var: cron_root.stdout_lines

- name: 'Disable root cron Mail Notify'
  tags: 'disable-cron-mail'
  shell:
    cmd: echo 'MAILTO=""' >> /var/spool/cron/crontabs/root
  notify: 'Restart cron Service'
  when: ansible_distribution == 'Ubuntu' and not "MAILTO=\"\"" in cron_root.stdout_lines
  ignore_errors: yes
