- name: 'Get root cron Content'
  tags: 'get-cron-root'
  shell:
    cmd: 'cat "{{ ROOT_CRON }}"'
  register: cron_root
  ignore_errors: yes

#- debug:
#    var: cron_root.stdout_lines

- name: 'Disable root cron Mail Notify'
  tags: 'disable-cron-mail'
  lineinfile:
    path: "{{ ROOT_CRON }}"
    line: 'MAILTO=""'
    insertbefore: BOF
  notify: 'Restart cron Service'
  when: not "MAILTO=\"\"" in cron_root.stdout_lines
  ignore_errors: yes
