- name: 'Set Profile'
  tags: 'set-profile'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { 'src':'history.sh.template', 'dest':'/etc/profile.d/history.sh' }
    - { 'src':'path.sh.template', 'dest':'/etc/profile.d/path.sh' }
    - { 'src':'locale.sh.template', 'dest':'/etc/profile.d/locale.sh' }
