- name: 'Optimize System Limits Config File'
  tags: 'opt-limits-config'
  template:
    src: 'moss.conf.template'
    dest: '/etc/security/limits.d/moss.conf'
    mode: 0644

- name: 'Optimize Systemd Limits'
  tags: 'opt-limits-systemd'
  lineinfile:
    dest: '/etc/systemd/system.conf'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { 'regexp':'^#?DefaultLimitCORE=', 'line':'DefaultLimitCORE=100000' }
    - { 'regexp':'^#?DefaultLimitNOFILE=', 'line':'DefaultLimitNOFILE=100000' }
