- name: 'Get "{{ BASHRC }}" Content'
  tags: 'set-bashrc'
  shell:
    cmd: 'cat {{ BASHRC }}'
  register: task_output

#- debug: var=task_output.stdout_lines

- name: 'Copy Extended bashrc file'
  tags: 'set-bashrc'
  template:
    src: 'bashrc.template'
    dest: '/tmp/moss-bashrc'
    mode: 0644
  when: not "# Moss - START" in bashrc.stdout_lines

- name: 'Append Extended Settings to bashrc'
  tags: 'set-bashrc'
  shell:
    cmd: 'cat /tmp/moss-bashrc >> {{ BASHRC }}'
  when: not "# Moss - START" in bashrc.stdout_lines

- name: 'Clean tmp bashrc'
  tags: 'set-bashrc'
  file:
    path: '/tmp/moss-bashrc'
    state: absent
  when: not "# Moss - START" in bashrc.stdout_lines
