- name: 'Change APT Repository Souce List for Ubuntu 20.04'
  tags: 'change-repo-ubuntu-20.04'
  copy:
    src: 'source.list.ubuntu-20.04'
    dest: '/etc/apt/sources.list'
    backup: yes
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution  == 'Ubuntu' and 
        ansible_distribution_version == '20.04'
