- name: 'Remove snaps'
  tags: 'remove-snapd'
  shell:
    cmd: "{{ item }}"
  with_items:
    - 'snap remove --purge lxd'
    - 'snap remove --purge core18'
    - 'snap remove --purge snapd'
  register: task_output
  ignore_errors: yes

- debug: var=task_output.stdout_lines

- name: 'Remove snapd Service'
  tags: 'remove-snapd'
  apt:
    name: 'snapd'
    state: absent
    purge: yes

- name: 'Clean snapd'
  tags: 'remove-snapd'
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '~/snap'
    - '/root/snap'
    - '/snap'
    - '/var/snap'
    - '/var/lib/snapd'
