- name: 'Stop cloud-init Service'
  tags: 'stop-cloud-init-service'
  systemd:
    name: cloud-init
    state: stopped
  ignore_errors: yes

- name: 'Remove cloud-init Service'
  tags: 'remove-cloud-init-service'
  apt:
    name: cloud-init
    state: absent
    purge: yes

- name: 'Clean cloud-init'
  tags: 'clean-cloud-init'
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cloud
    - /var/lib/cloud
    - /var/log/cloud-init.log
    - /var/log/cloud-init-output.log
