- name: 'Remove cloud-init Service'
  tags: 'remove-cloud-init'
  apt:
    name: cloud-init
    state: absent
    purge: yes
  register: task_output

- debug: var=task_output

- name: 'Clean cloud-init'
  tags: 'remove-cloud-init'
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cloud
    - /var/lib/cloud
    - /var/log/cloud-init.log
    - /var/log/cloud-init-output.log
